# version: '3'
services:
  backend:
    container_name: medease-backend
    build: ./backend
    ports:
      - "8001:8001"
    networks:
      - medease-net

  frontend:
    container_name: medease-frontend
    build: ./frontend
    ports:
      - "3000:80"
      # - "3000:5173"
    environment:
      - HOST=0.0.0.0
    networks:
      - medease-net

  flask-api:
    container_name: flask-api
    build: ./AI
    ports:
      - "5000:5000"
    networks:
      - medease-net

networks:
  medease-net:
